In [1]:
print 'Hello World'

Hello World


In [2]:
print 'hi there'

hi there


1.nbmbmn

In [3]:
# comment

In [4]:
pwd

u'/Users/sandeeppurva'

In [5]:
import numpy as np

In [6]:
my_list = [1,2,3,4]

In [7]:
my_array1 = np.array(my_list)

In [8]:
my_array1

array([1, 2, 3, 4])

In [9]:
my_list2 = [11,22,33,44]

In [10]:
my_lists = [my_list, my_list2]

In [11]:
my_array2 = np.array(my_lists)

In [12]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [13]:
my_array2.shape

(2, 4)

In [14]:
my_array2.dtype

dtype('int64')

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [18]:
np.arange(5,100,3)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50, 53,
       56, 59, 62, 65, 68, 71, 74, 77, 80, 83, 86, 89, 92, 95, 98])